export const ADD_MACHINES = 'ADD_MACHINES';
export const MACHINES_LOADING = 'MACHINES_LOADING';
export const MACHINES_FAILED = 'MACHINES_FAILED';

export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SIDEBAR_TABS_ACTIVE = 'SIDEBAR_TABS_ACTIVE';

export const ADD_DATA = 'ADD_DATA';
export const DATA_LOADING = 'DATA_LOADING';
export const DATA_FAILED = 'DATA_FAILED';