export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SIDEBAR_TABS_ACTIVE = 'SIDEBAR_TABS_ACTIVE';

export const ADD_DATA = 'ADD_DATA';
export const DATA_LOADING = 'DATA_LOADING';
export const DATA_FAILED = 'DATA_FAILED';

export const ADD_ZONES = "ADD_ZONES";
export const ZONES_LOADING = "ZONES_LOADING";
export const ZONES_FAILED = "ZONES_FAILED";

export const ADD_BARN = "ADD_BARN";
export const BARN_LOADING = "BARN_LOADING";
export const BARN_FAILED = "BARN_FAILED";

export const ADD_COW = "ADD_COW";
export const COW_LOADING = "COW_LOADING";
export const COW_FAILED = "COW_FAILED";

export const ADD_WATCHLIST = "ADD_WATCHLIST";
export const WATCHLIST_LOADING = "WATCHLIST_LOADING";
export const WATCHLIST_FAILED = "WATCHLIST_FAILED";

export const ADD_ORDERS = "ADD_ORDERS";
export const ORDERS_LOADING = "ORDERS_LOADING";
export const ORDERS_FAILED = "ORDERS_FAILED";

export const ADD_FEEDS = "ADD_FEEDS";
export const FEEDS_LOADING = "FEEDS_LOADING";
export const FEEDS_FAILED = "FEEDS_FAILED";

export const ADD_FEED_INFO_BY_TYPE = "ADD_FEED_INFO_BY_TYPE";
export const FEED_INFO_BY_TYPE_LOADING = "FEED_INFO_BY_TYPE_LOADING";
export const FEED_INFO_BY_TYPE_FAILED = "FEED_INFO_BY_TYPE_FAILED";

export const ADD_COMMODITIES = "ADD_COMMODITIES";
export const COMMODITIES_LOADING = "COMMODITIES_LOADING";
export const COMMODITIES_FAILED = "COMMODITIES_FAILED";

export const ADD_TOTAL_STORE_FEED_INFO = "ADD_TOTAL_STORE_FEED_INFO";
export const TOTAL_STORE_FEED_INFO_LOADING = "TOTAL_STORE_FEED_INFO_LOADING";
export const TOTAL_STORE_FEED_INFO_FAILED = "TOTAL_STORE_FEED_INFO_FAILED";

export const ADD_COWS = "ADD_COWS";
export const COWS_LOADING = "COWS_LOADING";
export const COWS_FAILED = "COWS_FAILED";

export const ADD_PERFORMANCE_METRICS = "ADD_PERFORMANCE_METRICS";
export const PERFORMANCE_METRICS_LOADING = "PERFORMANCE_METRICS_LOADING";
export const PERFORMANCE_METRICS_FAILED = "PERFORMANCE_METRICS_FAILED";

export const ADD_DASHBOARD_METRICS = "ADD_DASHBOARD_METRICS";
export const DASHBOARD_METRICS_LOADING = "DASHBOARD_METRICS_LOADING";
export const DASHBOARD_METRICS_FAILED = "DASHBOARD_METRICS_FAILED";